//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxModel.Data2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AX_2012_R2Entities : DbContext
    {
        public AX_2012_R2Entities()
            : base("name=AX_2012_R2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ElementType> ElementTypes { get; set; }
        public DbSet<Layer> Layers { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<ModelElement> ModelElements { get; set; }
        public DbSet<ModelElementData> ModelElementDatas { get; set; }
        public DbSet<ModelManifest> ModelManifests { get; set; }
    }
}
