//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxModel.Data2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelManifest
    {
        public int Id { get; set; }
        public int ModelId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Publisher { get; set; }
        public bool Signed { get; set; }
        public int CategoryId { get; set; }
        public int InstallMode { get; set; }
        public int VersionMajor { get; set; }
        public int VersionMinor { get; set; }
        public int VersionRevision { get; set; }
        public int VersionBuildNo { get; set; }
        public string Details { get; set; }
    
        public virtual Model Model { get; set; }
    }
}
