//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementType
    {
        public int ElementType1 { get; set; }
        public Nullable<int> ParentType { get; set; }
        public string ElementTypeName { get; set; }
        public string TreeNodeName { get; set; }
    }
}
