//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.ModelManifests = new HashSet<ModelManifest>();
        }
    
        public int Id { get; set; }
        public int LayerId { get; set; }
        public string State { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public Nullable<int> ModelGroupId { get; set; }
        public bool MarkedForRemoval { get; set; }
        public string InstalledBy { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<int> IsDirty { get; set; }
    
        public virtual Layer Layer { get; set; }
        public virtual ICollection<ModelManifest> ModelManifests { get; set; }
    }
}
