//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxModel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelElementData
    {
        public int LayerId { get; set; }
        public int ParentHandle { get; set; }
        public int ElementHandle { get; set; }
        public byte[] FileHeader { get; set; }
        public int BASEVERSION { get; set; }
        public int VERSION { get; set; }
        public int SAVECOUNT { get; set; }
        public int CONSISTENCYDATA { get; set; }
        public System.DateTime MODIFIEDDATETIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public System.DateTime CREATEDDATETIME { get; set; }
        public string CREATEDBY { get; set; }
        public int ModelId { get; set; }
        public int LegacyId { get; set; }
        public int ElementVersion { get; set; }
    }
}
